language: android
android:
  components:
    - build-tools-21.1.1
    - android-21
    - sysimg-21
    - extra
  licenses:
    - 'android-sdk-license-.+'
script:
  - ./gradlew assembleDebug

after_success:
  - ls -l *
  - find ../ -name "*.apk"